上传
24ITstudio/itstudio-website-backend pull request #8
Opened 2024-08-15 09:24 UTC by 1943432515

2024-08-15 11:11 UTC, litlighilit requested changes

2024-08-15 11:11 UTC, litlighilit commented on website/comment/models.py
> +    email_field = models.CharField(verbose_name='邮箱')
Why not name it as `email`?

2024-08-15 11:11 UTC, litlighilit commented on website/comment/models.py
> +    api = models.CharField()
what's this used for?

2024-08-15 11:11 UTC, litlighilit commented on website/comment/models.py
> +    email_field = models.CharField(verbose_name='邮箱')
`CharField` requires `max_length` as a parameter! (see the failed CI)

2024-08-15 11:11 UTC, litlighilit commented on website/comment/models.py
> +    api = models.CharField()
This `CharField` lacks `max_length` too

2024-08-15 11:48 UTC, 1943432515 commented on website/comment/models.py
> +    api = models.CharField()
这个参数我是看你文档上写的

2024-08-16 09:29 UTC, litlighilit requested changes

2024-08-16 09:29 UTC, litlighilit commented on website/comment/models.py
> +    email = models.CharField(max_length=20, verbose_name='邮箱')
Have you ever tested locally?
I mean try posting some data to your locally running developing server.

2024-08-16 09:30 UTC, litlighilit commented on website/comment/models.py
> +    email = models.CharField(max_length=20, verbose_name='邮箱')
Then you'll get it that writing as this won't work as expected

2024-08-17 06:57 UTC, litlighilit requested changes
Hand-writing a blank value, like a 4-charaters length string "null", but putting aside an existing blank value (a.k.a. None) is seldom an appreciative style especially in languages that has notation of null/nil like Python, unless there's certain reasons to do so.

2024-08-17 06:57 UTC, litlighilit commented on website/comment/models.py
> +    datetime = models.DateTimeField(auto_now_add=True, verbose_name='评论时间', default="null")
What the hell?
Why touch content, parent and datetime?

2024-08-17 06:57 UTC, litlighilit commented on website/comment/models.py
> +    datetime = models.DateTimeField(auto_now_add=True, verbose_name='评论时间', default="null")
None of them shall use "null" (a string!!!) as default!

2024-08-17 10:03 UTC, merged